<a href="https://colab.research.google.com/github/kornellewy/numpy-pandas-sklearn-scipy-exercise/blob/master/np_cw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [0]:
import numpy as np
import pandas as pd
import sklearn
import scipy

In [0]:
# 2. How to create a 1D array?
arrey1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# lub
arrey2 = np.arange(10)
print(arrey1)
print(arrey2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [0]:
# 3. How to create a boolean array?
# Create a 3×3 numpy array of all True’s
array_bool = np.ones((3,3), dtype=bool)
print(array_bool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [0]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Extract all odd numbers from array
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = array[array % 2 == 1]
print(array)

[1 3 5 7 9]


In [0]:
#5. How to replace items
# that satisfy a condition with another value in numpy array?
#  Replace all odd numbers in arr with -1
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array[array % 2 == 1] = -1
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [0]:
# 6. How to replace items that satisfy a condition without affecting 
#the original array?
# Replace all odd numbers in arr with -1 without changing arr
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(array % 2 == 1, -1, array)
print(out)
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [0]:
# 7. How to reshape an array?
# Convert a 1D array to a 2D array with 2 rows
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = array.reshape((2, 5))
print(array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
# 8. How to stack two arrays vertically?
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# method 1
c = np.concatenate([a, b], axis = 0)
# method 2
c = np.vstack([a, b])
# metohd 3
c = np.r_[a, b]
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [0]:
# 9. How to stack two arrays horizontally?
# Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
# method 1
c = np.concatenate([a, b], axis = -1)
# method 2
c = np.hstack([a, b])
# metohd 3
c = np.c_[a, b]
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [0]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Create the following pattern without hardcoding. 
# Use only numpy functions and the below input array a.
# input
a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
output = np.repeat(a, 3)
for i in range(3):
    output = np.concatenate([output, a], axis = 0)
print(output)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [0]:
# 11. How to get the common items between two python numpy arrays?
# Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
output = np.intersect1d(a,b)
print(output)

[2 4]


In [0]:
# 12. How to remove from one array those items that exist in another?
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
output = np.setdiff1d(a, b)
print(output)

[1 2 3 4]


In [0]:
# 13. How to get the positions where elements of two arrays match?
# Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
output = np.where(a==b)
print(output)

(array([1, 3, 5, 7]),)


In [0]:
# 14. How to extract all numbers between a given range from a numpy array?
# Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
# method 1
b = np.arange(5,11)
output = np.intersect1d(a,b)
# method 2
output = np.where((a>=5) & (a<=10))
output = a[output]
# method 3
output = a[(a>=5) & (a<=10)]
print(output)

[ 6  9 10]


In [0]:
# 15. How to make a python function that handles scalars 
# to work on numpy arrays?
# Convert the function maxx that works on two scalars,
#  to work on two arrays.
"""
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
"""
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a,b)


array([6., 7., 9., 8., 9., 7., 5.])

In [0]:
# 16. How to swap two columns in a 2d numpy array?
# Swap columns 1 and 2 in the array arr.
arr = np.arange(9).reshape(3,3)
# method 1
arr.T[[0,1]] = arr.T[[1,0]]
# method 2
arr = arr[:, [1,0,2]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
# 17. How to swap two rows in a 2d numpy array?
# Swap rows 1 and 2 in the array arr:
arr = np.arange(9).reshape(3,3)
# method 1
arr[[0,1]] = arr[[1,0]]
# method 2
arr = arr[[1,0,2], :]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
# 18. How to reverse the rows of a 2D array?
# Q. Reverse the rows of a 2D array arr.
a = np.arange(9).reshape(3,3)
b = a[::-1]
print(b)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [0]:
# 19. How to reverse the columns of a 2D array?
a = np.arange(9).reshape(3,3)
b = a[:, ::-1]
print(b)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [0]:
# 20. How to create a 2D array
# containing random floats between 5 and 10?
a = np.random.randint(low=5, high =10 ,size=(5,5))
print(a)

[[7 7 6 5 5]
 [9 8 9 7 5]
 [8 6 7 8 9]
 [9 6 8 9 9]
 [8 8 8 6 6]]


In [0]:
# 21. How to print only 3 decimal places in python numpy array?
a = np.random.random((5,3))
np.set_printoptions(precision=3)
print(a)

[[0.299 0.569 0.179]
 [0.533 0.647 0.142]
 [0.581 0.479 0.386]
 [0.44  0.405 0.442]
 [0.03  0.776 0.551]]


In [0]:
# 22. How to pretty print a numpy array 
# by suppressing the scientific notation (like 1e10)?
np.random.seed(100)
a = np.random.random([3,3])/1e3
np.set_printoptions(precision=6, suppress=True)
print(a)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [0]:
# 25. How to import a dataset with numbers and texts keeping 
# the text intact in python numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth',
         'species')
print(iris[:3])


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


In [0]:
# 26. How to extract a particular column from 1D array of tuples?
# Extract the text column species from the 
# 1D iris imported in previous question.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None)
speace = np.array([row[4] for row in iris])
speace

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-versicolor',
       b'Iris-versicolor', b'Iris-versicolor', b'Iris-versicolor',
       b'Iris-versicol

In [0]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?
# Convert the 1D iris to 2D array iris_2d 
# by omitting the species text field.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=None)
# method 1
iris = np.array([row.tolist()[:4] for row in iris])
# method 2
iris = np.genfromtxt(url, delimiter=',', dtype=None, usecols=[0,1,2,3])
print(iris)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [0]:
# 28. How to compute the mean, median, 
# standard deviation of a numpy array?
# Find the mean, median, 
# standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
info = (np.median(sepallength), np.mean(sepallength), np.std(sepallength))
print(info)

(5.8, 5.843333333333334, 0.8253012917851409)


In [0]:
# 29. How to normalize an array so the values range
# exactly between 0 and 1?
# Create a normalized form of iriss sepallength whose values
# range exactly between 0 and 1 so that the minimum has value
# 0 and maximum has value 1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength = (sepallength - np.min(sepallength))/np.ptp(sepallength)
print(sepallength)

[0.222222 0.166667 0.111111 0.083333 0.194444 0.305556 0.083333 0.194444
 0.027778 0.166667 0.305556 0.138889 0.138889 0.       0.416667 0.388889
 0.305556 0.222222 0.388889 0.222222 0.305556 0.222222 0.083333 0.222222
 0.138889 0.194444 0.194444 0.25     0.25     0.111111 0.138889 0.305556
 0.25     0.333333 0.166667 0.194444 0.333333 0.166667 0.027778 0.222222
 0.194444 0.055556 0.027778 0.194444 0.222222 0.138889 0.222222 0.083333
 0.277778 0.194444 0.75     0.583333 0.722222 0.333333 0.611111 0.388889
 0.555556 0.166667 0.638889 0.25     0.194444 0.444444 0.472222 0.5
 0.361111 0.666667 0.361111 0.416667 0.527778 0.361111 0.444444 0.5
 0.555556 0.5      0.583333 0.638889 0.694444 0.666667 0.472222 0.388889
 0.333333 0.333333 0.416667 0.472222 0.305556 0.472222 0.666667 0.555556
 0.361111 0.333333 0.333333 0.5      0.416667 0.194444 0.361111 0.388889
 0.388889 0.527778 0.222222 0.388889 0.555556 0.416667 0.777778 0.555556
 0.611111 0.916667 0.166667 0.833333 0.666667 0.805556 0.6111

In [0]:
# 30. How to compute the softmax score? 
# softmax  = e ^ x / sum(e ^ x)
# Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
e_x = np.array([np.exp(row) for row in sepallength])
softmax = np.array([row/np.sum(e_x) for row in e_x])
print(softmax)

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [0]:
# 31. How to find the percentile scores of a numpy array?
# Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5, 95])

array([4.6  , 7.255])

In [0]:
# 32. How to insert values at random positions in an array?
# Q. Insert np.nan values at 20 random positions in iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(100)
iris[np.random.randint(150, size=20),
     np.random.randint(4, size=20)] = np.nan
print(iris)


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [nan b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Iris-set

In [0]:
# 33. How to find the position of missing values in numpy array?
# Find the number and position of missing values 
# in iris sepallength (1st column)
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
a = np.argwhere(np.isnan(iris))
print(a)

[[  2   2]
 [ 13   3]
 [ 14   1]
 [ 17   3]
 [ 18   2]
 [ 27   1]
 [ 30   3]
 [ 38   0]
 [ 47   1]
 [ 56   2]
 [ 61   1]
 [ 63   3]
 [ 72   2]
 [ 80   0]
 [105   3]
 [106   0]
 [109   1]
 [113   0]
 [121   0]
 [147   3]]


In [0]:
# 34. How to filter a numpy array based on two or more conditions?
# Filter the rows of iris_2d that has petallength (3rd column) > 1.5
# and sepallength (1st column) < 5.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
warunek = (iris[:, 2]> 1.5) & (iris[:, 0] < 5)
a = iris[warunek]


In [0]:
# 35. How to drop rows that contain a missing value from a numpy array?
# Select the rows of iris_2d that does not have any nan value.
# Input
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris.shape)
# insert nan
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
# filter
iris =  iris[~np.isnan(iris).any(axis=1)]
# iris wiout nan
print(iris.shape)

(150, 4)
(130, 4)


In [0]:
#36. How to find the correlation between two columns of a numpy array?
# Find the correlation between SepalLength(1st column) and
# PetalLength(3rd column) in iris_2d
# Input
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:, 0], iris[:, 2])[0][1]

0.8717541573048718

In [0]:
# 37. How to find if a given array has any null values?
# Find out if iris_2d has any missing values.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
a = np.isnan(iris).any()
print(a)
# insert nan
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)]=np.nan
a = np.isnan(iris).any()
print(a)

False
True


In [0]:
# 38. How to replace all missing values with 0 in a numpy array?
# Replace all ccurrences of nan with 0 in numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
# insert nan
iris[np.random.randint(150, size=20), np.random.randint(4, size=20)]=np.nan
iris[np.argwhere(np.isnan(iris))] = 0
np.isnan(iris).any()

False

In [0]:
# 39. How to find the count of unique values in a numpy array?
# Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
keys, count=np.unique(iris[:, 3], return_counts=True)
a = dict(zip(keys, count))
print(a)

{b'0.1': 6, b'0.2': 28, b'0.3': 7, b'0.4': 7, b'0.5': 1, b'0.6': 1, b'1.0': 7, b'1.1': 3, b'1.2': 5, b'1.3': 13, b'1.4': 8, b'1.5': 12, b'1.6': 4, b'1.7': 2, b'1.8': 12, b'1.9': 5, b'2.0': 6, b'2.1': 6, b'2.2': 3, b'2.3': 8, b'2.4': 3, b'2.5': 3}


In [0]:
# 40. How to convert a numeric to a categorical (text) array?
# Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
#    Less than 3 --> 'small'
#    3-5 --> 'medium'
#    '>=5 --> 'large'
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Bin petallength 
petallength = np.digitize(iris[:, 2].astype('float'),[0,3,5,10])
# Map it to respective category
labelmap = {1: 'small', 2:'medium', 3:'large', 4:np.nan}
petallength = [labelmap[i] for i in petallength]

In [0]:
# 41. How to create a new column from existing columns of a numpy array?
# Create a new column for volume in iris_2d, where volume 
# is (pi x petallength x sepal_length^2)/3
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float, rest object
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
# petallength x sepal_length^2
y = np.multiply(iris[:, 2], np.power(iris[:, 0], 2))
# (pi x petallength x sepal_length^2)/3
y = ((np.pi * y)/3.0).astype('float')
# round
y = np.round(y, decimals=1)
y = np.reshape(y, (150,1))
np.append(iris, y, axis=1)


In [0]:
# 42. How to do probabilistic sampling in numpy?
# Randomly sample iris's species such that 
# setose is twice the number of versicolor and virginica
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# get speace name
keys=np.unique(iris[:, 4])
# map
y = keys.astype(str)
labelmap = {'Iris-setosa': 0.5,
            'Iris-versicolor':0.25,
            'Iris-virginica':0.25}
p = np.array([labelmap[i] for i in y])
sample = np.random.choice(y, size =10, p=p)
sample
# method 2 
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
# method 3
species = iris[:, 4]
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))
# check
#keys, count=np.unique(sample, return_counts=True)
#a = dict(zip(keys, count))
#print(a)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([79, 42, 29]))


In [0]:
# 43. How to get the second largest value of an array
# when grouped by another array?
# What is the value of second longest petallength of species setosa
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float, rest object
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
# bierzemy tylko Iris-setosa tym : [iris[:,4] == b'Iris-setosa' 
# i potem 2 kolumne: , [2]
setosa = iris[iris[:,4] == b'Iris-setosa', [2]]
# tylko unikalne
setosa = np.unique(setosa)
# sortujemy
setosa = np.sort(setosa)
# bierzemy 2 najwieksza wartosc
setosa[-2]


1.7

In [0]:
# 44. How to sort a 2D array by a column 
# Sort the iris dataset based on sepallength column.
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float, rest object
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
# sortujemy
iris = iris[iris[:,0].argsort()]
iris

In [0]:
# 45. How to find the most frequent value in a numpy array?
# Find the most frequent value of petal length (3rd column)
# in iris dataset.
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float, rest object
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
# method 2
# get column
petallength = iris[:, 2]
# get unique values and count
(petallength, count) = np.unique(petallength, return_counts=True)
value = np.argmax(count)
print(petallength[value])

1.5


In [0]:
# 46. How to find the position of the first occurrence of a 
# value greater than a given value?
# Find the position of the first occurrence of a value greater than 1.0 in 
# petalwidth 4th column of iris dataset.
url='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris=np.genfromtxt(url, delimiter=',', dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float, rest object
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
petalwidth = iris[:, 3]
index = np.argwhere(petalwidth>1.0)
print(index[0])

[50]


In [0]:
# 47. How to replace all values greater than a given value to
# a given cutoff?
# From the array a, replace all values greater
# than 30 to 30 and less than 10 to 10.
# method 1
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a = np.clip(a, 10, 30)
print(a)
# method 2
np.random.seed(100)
a = np.random.uniform(1,50, 20)
# replace all values greater than 30 to 30
a = np.where(a > 30, 30, a)
# replace all values less than 10 to 10.
a = np.where(a < 10, 10, a)
print(a)

[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]
[27.626842 14.6401   21.801362 30.       10.       10.       30.
 30.       10.       29.179573 30.       11.250904 10.081083 10.
 11.765177 30.       30.       10.       30.       14.429614]


In [0]:
# 48. How to get the positions of top n values from a numpy array?
# Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)
b = np.argpartition(a, -5)[-5:]
b

array([18,  7,  3, 10, 15])

In [0]:
# 49. How to compute the row wise counts of all possible values 
# in an array?
# Compute the counts of unique values row-wise.
np.random.seed(100)
a = np.random.randint(1,11,size=(6, 10))
def counts_of_all_values_rowwise(arr):
    c = [np.unique(row, return_counts=True) for row in arr]
    output =[]
    for a,b in c:
        row =[]
        for i in np.unique(arr):
            if i in a:
                row.append(int(b[a==i]))
            else:
                row.append(0)
        output.append(row)
    # print list
    for i in output:
        print(i)      
print(np.arange(1,11))
counts_of_all_values_rowwise(a)

[ 1  2  3  4  5  6  7  8  9 10]
[1, 0, 2, 1, 1, 1, 0, 2, 2, 0]
[2, 1, 3, 0, 1, 0, 1, 0, 1, 1]
[0, 3, 0, 2, 3, 1, 0, 1, 0, 0]
[1, 0, 2, 1, 0, 1, 0, 2, 1, 2]
[2, 2, 2, 0, 0, 1, 1, 1, 1, 0]
[1, 1, 1, 1, 1, 2, 0, 0, 2, 1]


In [0]:
# 50. How to convert an array of arrays into a flat 1d array?
# Convert array_of_arrays into a flat linear 1d array.
a = np.arange(3)
b = np.arange(3,7)
c = np.arange(7,10)
array_of_arrays = np.array([a, b, c])
d = np.concatenate(array_of_arrays)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 51. How to generate one-hot encodings for an array in numpy?
# Compute the one-hot encodings (dummy binary variables for each unique 
# value in the array)
np.random.seed(101) 
a = np.random.randint(1,4, size=6)
b = np.zeros((6, 3))
b[np.arange(6), a-1] = 1
b

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [0]:
# 52. How to create row numbers grouped by a categorical variable?
# Create row numbers grouped by a categorical variable. Use the following 
# sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
# method 1 beter
def row_numbers_grouped_by_categorical(species_small):
    temp = ''
    idx = 0
    species_small2 = []
    for name in species_small:
        name = str(name)
        if (name == temp):
            idx += 1
            species_small2.append(str(idx)) 
        else:
            temp = name
            idx = 0
            species_small2.append(str(idx)) 
    return species_small2
row_numbers_grouped_by_categorical(species_small)
# method 2
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [0]:
# 53. How to create groud ids based on a given categorical variable?
# Create group ids based on a given categorical variable. 
# Use the following sample from iris species as input.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
_, species_small =np.unique(species_small, return_inverse=True)
print(species_small)

[0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 2 2]


In [0]:
# 54. How to rank items in an array using numpy?
# Create the ranks for the given numeric array a.
np.random.seed(10)
a = np.random.randint(2000000, size=10)
# method 1
temp = a.argsort()
rank = np.empty_like(temp)
rank[temp] = np.arange(len(a))
rank
# method 2 beter bo krocej
b=a.argsort().argsort()
b

array([4, 7, 1, 8, 5, 0, 2, 6, 9, 3])

In [0]:
# 55. How to rank items in a multidimensional array using numpy?
# Create a rank array of the same shape as a given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
_, b =np.unique(a, return_inverse=True)
c = (b+6 - b.max()).reshape(a.shape)
c

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


array([[3, 1, 4, 0, 6],
       [5, 6, 2, 3, 0]])

In [0]:
# 56. How to find the maximum value in each row of a numpy array 2d?
# Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
# method  1 beter
b = np.amax(a, axis=1)
# METHOD 2
c = [row[row.argmax()] for row in a]


In [0]:
# 57. How to compute the min-by-max for each row for a numpy array 2d?
# Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
b = np.divide(np.amin(a, axis=1), np.amax(a, axis=1))

In [0]:
# 58. How to find the duplicate records in a numpy array?
# Find the duplicate entries (2nd occurrence onwards) in the given numpy array 
# and mark them as True. First time occurrences should be False.
np.random.seed(100)
a = np.random.randint(0, 5, 10)
# method 1
b = []
c = []
for i in a:
    i = int(i)
    if i in b:
        c.append(True)
    else:
        b.append(int(i))
        c.append(False)
# method 2 beter
np.random.seed(100)
a = np.random.randint(0, 5, 10)
# Create an all True array
out = np.full(a.shape[0], True)
# Find the index positions of unique elements
_, idx = np.unique(a, return_index=True)
# Mark those positions as False
out[idx] = False

In [0]:
# 59. How to find the grouped mean in numpy?
# Find the mean of a numeric column grouped by a 
# categorical column in a 2D numpy array
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# conver col 0, 1, 2, 3 to float
iris[:, [0,1,2,3]] = iris[:, [0,1,2,3]].astype('float')
# convert col 5 to str
iris[:, 4] = iris[:, 4].astype('str')
# mean for all coluns
keys = np.unique(iris[:, 4])
b =[]
for key in keys:
    a = iris[np.where(iris[:, 4]==key), :-1].mean()
    b.append((key, a))
# mean for 1 col np. 1
keys = np.unique(iris[:, 4])
b =[]
for key in keys:
    a = iris[np.where(iris[:, 4]==key), 1].mean()# 1 is nr of col
    b.append((key, a))

In [0]:
# 60. How to convert a PIL image to numpy array?
# Import the image from the following URL and 
# convert it to a numpy array.
from io import BytesIO
from PIL import Image
import PIL, requests
url='https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
img = requests.get(url)
# read as img
img = Image.open(BytesIO(img.content))
# img to np array
img = np.asarray(img)
# np array to img
img = PIL.Image.fromarray(np.uint8(img))


In [0]:
# 61. How to drop all missing values from a numpy array?
# Drop all nan values from a 1D numpy array
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = a[~np.isnan(a)]
a

array([1., 2., 3., 5., 6., 7.])

In [0]:
# 62. How to compute the euclidean distance between two arrays?
# Compute the euclidean distance between two arrays a and b.
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [0]:
# 63. How to find all the local maxima (or peaks) in a 1d array?
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
# method 1
from scipy.signal import argrelextrema
index = argrelextrema(a, np.greater)
# method 2
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1

In [0]:
# 64. How to subtract a 1d array from a 2d array, where each item of 1d 
# array subtracts from respective row?
# Subtract the 1d array b_1d from the 2d array a_2d, such that each item of
# b_1d subtracts from respective row of a_2d.
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1])
a = np.subtract(a_2d, b_1d)
a

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [0]:
# 65. How to find the index of n'th repetition of an item in an array
# Find the index of 5th repetition of number 1 in x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
# method 1
n= 5
i = np.where(x==1)[0][n-1]
print(i)
# method 2
def idex(x):
    n = 0
    idx = 0
    for i in x:
        if (int(i) == 1):
            n += 1
            if (n==5):
                return idx
        idx += 1

8


In [0]:
# 66. How to convert numpy's datetime64 object to datetime's
# datetime object?
# Convert numpy's datetime64 object to datetime's datetime object
# method 1
from datetime import datetime
import pandas as pd
dt64 = np.datetime64('2018-02-25 22:10:10')
dt = dt64.astype(datetime)
# method 2
dt =  pd.Timestamp(dt64).to_pydatetime()

In [0]:
# 67. How to compute the moving average of a numpy array?
# Compute the moving average of window size 3, for the given 1D array.
np.random.seed(100)
b = np.random.randint(10, size=10)
a = np.convolve(b, np.ones((3,))/3, mode='valid')
c = pd.Series(b).rolling(window=3).mean().iloc[3-1:].values

In [0]:
# 68. How to create a numpy array sequence given only the starting point,
# length and the step?
i =5
b = []
for n in range(10):
    b.append(i)
    i = i+3

In [0]:
# 69. How to fill in missing dates in an irregular series of numpy dates?
# Given an array of a non-continuous sequence of dates. Make it a continuous
# sequence of dates, by filling in the missing dates.
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25')
, 2)
a= np.arange(dates[0], dates[-1], 1)
a = np.hstack([a, dates[-1]])


In [0]:
# 70. How to create strides from a given 1D array?
# From the given 1d array arr, generate a 2d matrix using strides, with
# a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5],
# [4,5,6,7]..]
# method 1 faster
a = []
b = np.arange(4)
a.append(b)
for i in range(4):
    b=np.add(b,2)
    a.append(b)
a = np.array(a)
# method 2
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])
print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
