<a href="https://colab.research.google.com/github/kornellewy/numpy-pandas-sklearn-scipy-exercise/blob/master/pandas_cw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# # https://www.machinelearningplus.com/python/101-pandas-exercises-python/

In [0]:
import numpy as np
import pandas as pd

In [0]:
# 2. How to create a series from a list, numpy array and dict?
# Create a pandas series from each of the items below: a list,
#  numpy and a dictionary
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
a = pd.Series(mylist)
b = pd.Series(myarr)
c = pd.Series(mydict) 

In [0]:
# 3. How to convert the index of a series into a column of a dataframe?
# Convert the series ser into a dataframe with its index as another column
# on the dataframe.
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
a = pd.Series(mydict)
a = a.to_frame().reset_index()

In [0]:
 #4. How to combine many series to form a dataframe?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
a = pd.concat([ser1, ser2], axis=1)

In [0]:
# 5. How to assign name to the series’ index?
# give a name to the series ser calling it ‘alphabets’.
a = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
a.name = 'alphabets'

In [279]:
# 6. How to get the items of series A not present in series B?
# From ser1 remove items present in ser2.
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([4, 5, 6, 7, 8])
a[~a.isin(b)]

0    1
1    2
2    3
dtype: int64

In [280]:
# 7. How to get the items not common to both series A and series B?
# Get all items of ser1 and ser2 not common to both.
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([4, 5, 6, 7, 8])
c = pd.Series(np.union1d(a,b))
d = pd.Series(np.intersect1d(a,b))
c[~c.isin(d)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [281]:
# 8. How to get the minimum, 25th percentile,
# median, 75th, and max of a numeric series?
# Compute the minimum, 25th percentile, median, 
# 75th, and maximum of ser.
state = np.random.RandomState(100)
a = pd.Series(state.normal(10, 5, 25))
b = pd.Series(np.percentile(a, q=[0, 25, 50, 75, 100]))
b

0    1.2512
1    7.7099
2   10.9226
3   13.3636
4   18.0949
dtype: float64

In [282]:
# 9. How to get frequency counts of unique items of a series?
# Calculte the frequency counts of each unique value ser.
a = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
a.value_counts()

b    7
f    5
d    4
c    4
h    4
a    3
e    2
g    1
dtype: int64

In [0]:
# 10. How to keep only top 2 most frequent values
# as it is and replace everything else as ‘Other’?
# From ser, keep the top 2 most frequent items as it
# is and replace everything else as ‘Other’
a = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
b = a.value_counts().index[:2]
a[~a.isin(b)] = 'Other'

In [284]:
# 11. How to bin a numeric series to 10 groups of equal size?
# in the series ser into 10 equal deciles and
# replace the values with the bin name.
a = pd.Series(np.random.random(20))
b = pd.qcut(a, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()
b

0    8th
1    7th
2    5th
3    9th
4    1st
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

In [285]:
# 12. How to convert a numpy array to a dataframe of given shape? (L1)
#  Reshape the series ser into a dataframe with 7 rows and 5 columns
ser = pd.Series(np.random.randint(1, 10, 35))
ser = pd.DataFrame(data=ser.values.reshape(7,5))
ser

0  1  2  3  4
0  3  6  8  4  2
1  2  8  8  3  6
2  4  5  8  5  3
3  1  2  6  5  5
4  8  3  2  9  1
5  7  6  7  4  1
6  2  9  8  6  6

In [286]:
# 13. How to find the positions of 
# numbers that are multiples of 3 from a series?
# Find the positions of numbers that are multiples of 3 from ser.
np.random.seed(100)
a = pd.Series(np.random.randint(1, 10, 7))
b = pd.Series(np.where(a%3==0))
print(b)

0    [0, 1]
dtype: object


In [287]:
# 14. How to extract items at given positions from a series
# From ser, extract the items at positions in list pos.
a = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
b = [0, 4, 8, 14, 20]
c = a.take(b)
c

0     a
4     e
8     i
14    o
20    u
dtype: object

In [288]:
#15. How to stack two series vertically and horizontally ?
#Stack ser1 and ser2 vertically and horizontally (to form a dataframe).
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
# vertically
ser3 = ser1.append(ser2)
# horizontally
ser3 = pd.concat([ser1 ,ser2], axis=1) 
ser3

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [289]:
# 16. How to get the positions of items of series A in another series B?
# Get the positions of items of ser2 in ser1 as a list.
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
ser3 = ser1[ser1.isin(ser2)].index
ser3 

Int64Index([0, 4, 5, 8], dtype='int64')

In [290]:
# 17. How to compute the mean squared error on a truth and predicted series?
# Compute the mean squared error of truth and pred series.
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
mse = np.mean( np.power( np.subtract( truth, pred ), 2 ) )
mse

0.24287166298707774

In [291]:
# 18. How to convert the first character
# of each element in a series to uppercase?
# Change the first character of each word to upper case 
# in each word of ser.
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser = [word.capitalize() for word in ser]
ser

['How', 'To', 'Kick', 'Ass?']

In [292]:
#19. How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
word_count = pd.Series([len(word) for word in ser])
word_count

0    3
1    2
2    4
3    4
dtype: int64

In [0]:
# 20. How to compute difference of differences between consequtive
# numbers of a series?
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
serd = ser.diff().tolist()
serdd = ser.diff().diff().tolist()

In [294]:
# 21. How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser = pd.to_datetime(ser)
ser

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [0]:
#22. How to get the day of month, week number,
# day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser = pd.to_datetime(ser)
days = ser.dt.day.tolist()
weeks = ser.dt.week.tolist()
days_num_year = ser.dt.dayofyear.tolist()
days_num_week = ser.dt.weekday_name.tolist()


In [296]:
# 23. How to convert year-month string to dates corresponding to the 4th day of the month?
# Change ser to dates that start with 4th of the respective months.
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser = pd.to_datetime(ser)
ser = ser.apply(lambda dt: dt.replace(day=4))
ser

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [297]:
# 24. How to filter words that contain atleast 2 vowels from a series?
# From ser, extract words that contain atleast 2 vowels.
# słowa zawierające co najmniej 2 samogłoski.
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
vowels =  list('aeiouAEIOU')
def filter_vowels(words, count):
    result = []
    for word in words:
        if (sum(p in vowels for p in word) >= count):
             result.append(word)
    return result
output = filter_vowels(ser.to_list(), 2)
output

['Apple', 'Orange', 'Money']

In [298]:
# 25. How to filter valid emails from a series?
# Extract the valid emails from the series emails. 
# The regex pattern for valid emails is provided as reference.
import re
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
emails =  emails.str.findall(pattern, flags=re.IGNORECASE)
emails = emails.drop(0)
emails

1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [299]:
# 26. How to get the mean of a series grouped by another series?
# Compute the mean of weights of each fruit.
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weight = pd.Series(np.linspace(1, 10, 10))
weight.groupby(fruit).mean()

apple    4.0000
banana   6.5000
dtype: float64

In [300]:
# 27. How to compute the euclidean distance between two series?
# Compute the euclidean distance between series (points) p and q
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
dist = np.linalg.norm(p-q)
dist

18.16590212458495

In [301]:
# 28. How to find all the local maxima (or peaks) in a numeric series?
# Get the positions of peaks (values surrounded by smaller values on both sides)
# in ser.
a = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3]).values
from scipy.signal import argrelextrema
index = argrelextrema(a, np.greater)
index

(array([1, 5, 7]),)

In [302]:
# 29. How to replace missing spaces in a string with the least frequent 
# character?
# eplace the spaces in my_str with the least frequent character.
s = 'dbc deb abed gade'
a = np.array(list(s))
keys, count  = np.unique(a, return_counts=True)
b = keys[np.argmin(count)]
c = np.where(a == ' ', b, a)
c=c.tolist()
c=''.join(c)
c

'dbccdebcabedcgade'

In [303]:
# 30. How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends 
# (saturdays) after that having random numbers as values?
np.random.seed(100)
a = pd.Series(np.random.randint(1,10,10), 
              pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
a


2000-01-01    9
2000-01-08    9
2000-01-15    4
2000-01-22    8
2000-01-29    8
2000-02-05    1
2000-02-12    5
2000-02-19    3
2000-02-26    6
2000-03-04    3
Freq: W-SAT, dtype: int64

In [304]:
# 31. How to fill an intermittent time series so all missing dates show up
# with values of previous non-missing date?
a = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01',
                                                     '2000-01-03',
                                                     '2000-01-06',
                                                     '2000-01-08']))
index = a.index[a.apply(np.isnan)]
prev_index = (a[index].shift(-2, 'D')).index
a = a.fillna(value=a[prev_index].values[0].astype(int))
a

2000-01-01    1.0000
2000-01-03   10.0000
2000-01-06    3.0000
2000-01-08    3.0000
dtype: float64

In [305]:
# 32. How to compute the autocorrelations of a numeric series?
# Compute autocorrelations for the first 10 lags of ser. Find out which 
# lag has the largest correlation.
np.random.seed(100)
a = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
b = [a.autocorr(i).round(2) for i in range(11)]
b

[1.0, 0.21, 0.08, 0.41, 0.21, 0.01, 0.03, 0.4, 0.16, 0.39, -0.02]

In [0]:
# 33. How to import only every nth row from a csv file 
# to create a dataframe?
# Import every 50th row of BostonHousing dataset as a dataframe.
# method 1
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 chunksize=50)
df2 = pd.DataFrame()
for i in df:
    df2 = df2.append(i.iloc[0,:])
# method 2
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()

In [307]:
# 34. How to change column values when importing csv to a dataframe?
# import the boston housing dataset, but while importing change the 'medv'
# (median house value) column so that values < 25 becomes ‘Low’ 
# and > 25 becomes ‘High’.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 converters={'medv': lambda x: 'high' if float(x) > 25 else 'low'})
df

crim      zn   indus  chas    nox  ...  tax  ptratio        b  lstat  \
0   0.0063 18.0000  2.3100     0 0.5380  ...  296  15.3000 396.9000 4.9800   
1   0.0273  0.0000  7.0700     0 0.4690  ...  242  17.8000 396.9000 9.1400   
2   0.0273  0.0000  7.0700     0 0.4690  ...  242  17.8000 392.8300 4.0300   
3   0.0324  0.0000  2.1800     0 0.4580  ...  222  18.7000 394.6300 2.9400   
4   0.0691  0.0000  2.1800     0 0.4580  ...  222  18.7000 396.9000 5.3300   
..     ...     ...     ...   ...    ...  ...  ...      ...      ...    ...   
501 0.0626  0.0000 11.9300     0 0.5730  ...  273  21.0000 391.9900 9.6700   
502 0.0453  0.0000 11.9300     0 0.5730  ...  273  21.0000 396.9000 9.0800   
503 0.0608  0.0000 11.9300     0 0.5730  ...  273  21.0000 396.9000 5.6400   
504 0.1096  0.0000 11.9300     0 0.5730  ...  273  21.0000 393.4500 6.4800   
505 0.0474  0.0000 11.9300     0 0.5730  ...  273  21.0000 396.9000 7.8800   

     medv  
0     low  
1     low  
2    high  
3    high  
4    high  
..    ...  
501   low  
502   low  
503   low  
504   low  
505   low  

[506 rows x 14 columns]

In [308]:
#35.How to create a dataframe with rows as strides from a given series?
L = pd.Series(range(15))
L = np.array([0,1,2,3])
#
def zad35(L, n):
    L2 = L
    for i in range(n):
        L2 = np.add(L2, 2)
        L = np.vstack((L, L2))
    return L
L = pd.DataFrame(zad35(L, 6))
L


0   1   2   3
0   0   1   2   3
1   2   3   4   5
2   4   5   6   7
3   6   7   8   9
4   8   9  10  11
5  10  11  12  13
6  12  13  14  15

In [309]:
# 36. How to import only specified columns from a csv file?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv',
                 usecols=['medv', 'crim'])
df.head()

crim    medv
0 0.0063 24.0000
1 0.0273 21.6000
2 0.0273 34.7000
3 0.0324 33.4000
4 0.0691 36.2000

In [310]:
# 37. How to get the nrows, ncolumns, datatype, summary stats of each 
# column of a dataframe? Also get the array and list equivalent.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#  number of rows and columns
print(df.shape)
# datatypes
print(df.dtypes)
# how many columns under each dtype
print(df.get_dtype_counts())
print(df.dtypes.value_counts())
# summary statistics
df_stats = df.describe()
# numpy array 
df_arr = df.values
# list
df_list = df.values.tolist()

(93, 27)
Manufacturer       object
Model              object
Type               object
Min.Price         float64
Price             float64
                   ...   
Rear.seat.room    float64
Luggage.room      float64
Weight            float64
Origin             object
Make               object
Length: 27, dtype: object
float64    18
object      9
dtype: int64
float64    18
object      9
dtype: int64


In [311]:
# 38. How to extract the row and column number of a particular cell with
# given criterion?
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# index
df['Price'].idxmax()
# value
df['Price'][df['Price'].idxmax()]
# get row
df.iloc[df['Price'].idxmax()]

Manufacturer           Mercedes-Benz
Model                           300E
Type                         Midsize
Min.Price                    43.8000
Price                        61.9000
                         ...        
Rear.seat.room                   NaN
Luggage.room                 15.0000
Weight                     3525.0000
Origin                       non-USA
Make              Mercedes-Benz 300E
Name: 58, Length: 27, dtype: object

In [312]:
# 39. How to rename a specific columns in a dataframe?
# Rename the column Type as CarType in df and replace 
# the ‘.’ in column names with ‘_’.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# Rename the column Type as CarType in df
df = df.rename(columns={"Type": "CarType"})
# replace the ‘.’ in column names with ‘_’. 
names =  df.columns.values.tolist()
namess  = [n.replace('.', '_') for n in names]
df.columns = namess
df.head(5)

Manufacturer    Model  CarType  Min_Price   Price  ...  Rear_seat_room  \
0        Acura  Integra    Small    12.9000 15.9000  ...         26.5000   
1          NaN   Legend  Midsize    29.2000 33.9000  ...         30.0000   
2         Audi       90  Compact    25.9000 29.1000  ...         28.0000   
3         Audi      100  Midsize        nan 37.7000  ...         31.0000   
4          BMW     535i  Midsize        nan 30.0000  ...         27.0000   

   Luggage_room    Weight   Origin           Make  
0           nan 2705.0000  non-USA  Acura Integra  
1       15.0000 3560.0000  non-USA   Acura Legend  
2       14.0000 3375.0000  non-USA        Audi 90  
3       17.0000 3405.0000  non-USA       Audi 100  
4       13.0000 3640.0000  non-USA       BMW 535i  

[5 rows x 27 columns]

In [313]:
# 40. How to check if a dataframe has any missing values?
# Check if df has any missing values.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().values.any()

True

In [314]:
# 41. How to count the number of missing values in each column?
# Count the number of missing values in each column of df. 
# Which column has the maximum number of missing values?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
# df.columns.values.tolist()
df.isna().sum().idxmax()

'Luggage.room'

In [0]:
# 42. How to replace missing values of multiple numeric 
# columns with the mean?
# Replace missing values in Min.Price and Max.Price columns with
# their respective mean.
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price']=df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price']=df['Max.Price'].fillna(df['Max.Price'].mean())


In [0]:
# 43. How to use apply function on existing columns with global variables
# as additional arguments?
# In df, use apply method to replace the missing values in Min.Price with
# the column’s mean and those in Max.Price with the column’s median
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price']=df['Min.Price'].fillna(df.mean())
df['Max.Price']=df['Max.Price'].fillna(df['Max.Price'].median())

In [317]:
# 44. How to select a specific column from a dataframe as a dataframe 
# instead of a series?
# Get the first column (a) in df as a dataframe 
# (rather than as a Series).
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
df['a']

0     0
1     5
2    10
3    15
Name: a, dtype: int64

In [318]:
# 45. How to change the order of columns of a dataframe?
# In df, interchange columns 'a' and 'c'.
# Create a generic function to interchange two columns,
# without hardcoding column names.
# Sort the columns in reverse alphabetical order,
# that is colume 'e' first through column 'a' last
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
# interchange columns 'a' and 'c'
names =  df.columns.values.tolist()
names[0], names[2] = names[2], names[0]
df.columns = names
# Create a generic function to interchange two columns
def swap_col_names(df, i, j):
    names =  df.columns.values.tolist()
    names[i], names[j] = names[j], names[i]
    df.columns = names
    return df
df = swap_col_names(df, 2, 0)
# Sort the columns in reverse alphabetical order,
# that is colume 'e' first through column 'a' last
names =  df.columns.values.tolist()
names.reverse()
names

['e', 'd', 'c', 'b', 'a']

In [319]:
# 46. How to set the number of rows and columns displayed in the output?
# Change the pamdas display settings on printing the dataframe df it shows
# a maximum of 10 rows and 10 columns.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
pd.options.display.max_rows = 10
pd.options.display.max_columns =10
df

Manufacturer    Model     Type  Min.Price   Price  ...  Rear.seat.room  \
0         Acura  Integra    Small    12.9000 15.9000  ...         26.5000   
1           NaN   Legend  Midsize    29.2000 33.9000  ...         30.0000   
2          Audi       90  Compact    25.9000 29.1000  ...         28.0000   
3          Audi      100  Midsize        nan 37.7000  ...         31.0000   
4           BMW     535i  Midsize        nan 30.0000  ...         27.0000   
..          ...      ...      ...        ...     ...  ...             ...   
88   Volkswagen  Eurovan      Van    16.6000 19.7000  ...         34.0000   
89   Volkswagen   Passat  Compact    17.6000 20.0000  ...         31.5000   
90   Volkswagen  Corrado   Sporty    22.9000 23.3000  ...         26.0000   
91        Volvo      240  Compact    21.8000 22.7000  ...         29.5000   
92          NaN      850  Midsize    24.8000 26.7000  ...         30.0000   

    Luggage.room    Weight   Origin                Make  
0            nan 2705.0000  non-USA       Acura Integra  
1        15.0000 3560.0000  non-USA        Acura Legend  
2        14.0000 3375.0000  non-USA             Audi 90  
3        17.0000 3405.0000  non-USA            Audi 100  
4        13.0000 3640.0000  non-USA            BMW 535i  
..           ...       ...      ...                 ...  
88           nan 3960.0000      NaN  Volkswagen Eurovan  
89       14.0000 2985.0000  non-USA   Volkswagen Passat  
90       15.0000 2810.0000  non-USA  Volkswagen Corrado  
91       14.0000 2985.0000  non-USA           Volvo 240  
92       15.0000 3245.0000  non-USA           Volvo 850  

[93 rows x 27 columns]

In [320]:
# 47. How to format or suppress scientific notations in a pandas dataframe?
# suppress scientific notations like ‘e-03’ in df and print upto 4 numbers 
# after decimal.
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
pd.options.display.float_format = '{:.4f}'.format
df

random
0  0.0000
1  0.0000
2  0.1017
3  0.0000

In [321]:
# 48. How to format all the values in a dataframe as percentages?
# Format the values in column 'random' of df as percentages.
df = pd.DataFrame(np.random.random(4), columns=['random'])
df['random'] = pd.Series(["{0:.2f}%".format(val * 100) for val in df['random']], index = df.index)
df

random
0  59.88%
1  60.38%
2  10.51%
3  38.19%

In [322]:
# 50. How to create a primary key index by combining relevant columns?
# In df, Replace NaNs with ‘missing’ in columns 'Manufacturer', 'Model' and
# 'Type' and create a index as a combination of these three columns and
# check if the index is a primary key.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv',
                 usecols=[0,1,2,3,5])
df = df.fillna('missing')
df['dupa'] = df.apply(lambda row: str(row['Manufacturer']+row['Model']), axis=1)
df


Manufacturer    Model     Type Min.Price Max.Price               dupa
0         Acura  Integra    Small   12.9000   18.8000       AcuraIntegra
1       missing   Legend  Midsize   29.2000   38.7000      missingLegend
2          Audi       90  Compact   25.9000   32.3000             Audi90
3          Audi      100  Midsize   missing   44.6000            Audi100
4           BMW     535i  Midsize   missing   missing            BMW535i
..          ...      ...      ...       ...       ...                ...
88   Volkswagen  Eurovan      Van   16.6000   22.7000  VolkswagenEurovan
89   Volkswagen   Passat  Compact   17.6000   22.4000   VolkswagenPassat
90   Volkswagen  Corrado   Sporty   22.9000   23.7000  VolkswagenCorrado
91        Volvo      240  Compact   21.8000   23.5000           Volvo240
92      missing      850  Midsize   24.8000   28.5000         missing850

[93 rows x 6 columns]

In [323]:
# 51. How to get the row number of the nth largest value in a column?
# Find the row position of the 5th largest value of column 'a' in df.
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1),
                  columns=list('abc'))
a =  df['a'].idxmax()
print(df)
print(a)

    a   b   c
0   8  14   7
1  13  19   1
2  25   3  22
3  11  18   9
4  14  11  18
5  22   5  19
6   9  28  28
7  20  22  15
8   1  14  26
9  13  11   4
2


In [324]:
# 52. How to find the position of the nth largest value greater than a 
# given value?
# In ser, find the position of the 2nd largest value
# greater than the mean.
#method1 fast
a= pd.Series(np.random.randint(1, 100, 15))
b= np.argwhere(a > a.mean())[1]
#method 2
a = pd.Series(np.random.randint(1, 100, 15))
s = a.mean()
b = a[a > s]
b = b.sort_values()
b = b.index[1]


/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:56: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  return getattr(obj, method)(*args, **kwds)


In [325]:
# 53. How to get the last n rows of a dataframe with row sum > 100?
# Get the last two rows of df whose row sum is greater than 100.
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
# method 1 fast
# print row sums
rowsums = df.apply(np.sum, axis=1)
# last two rows with row sum greater than 100
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
# method 2
df['sum'] = [np.sum(df.iloc[[i]].values) for i in range(df.shape[0])]
a = df['sum'][df['sum']>100].index[-1]
b = df['sum'][df['sum']>100].index[-2]
print(a, b)

14 12


In [326]:
# 54. How to find and cap outliers from a series or dataframe column?
# Replace all values of ser in the lower 5%ile and greater than
# 95%ile with respective 5th and 95th %ile value.
a = pd.Series(np.logspace(-2, 2, 30))
minimal_value =  np.multiply(a[a.idxmax()],0.05)
maximal_value =  np.multiply(a[a.idxmax()],0.95)
a = np.where(a<=minimal_value, minimal_value, a)
a = np.where(a>=maximal_value, maximal_value, a)
a

array([ 5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
        5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
        5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
        5.        ,  5.        ,  5.        ,  5.        ,  5.        ,
        5.73615251,  7.88046282, 10.82636734, 14.87352107, 20.43359718,
       28.07216204, 38.56620421, 52.98316906, 72.78953844, 95.        ])

In [327]:
# 55. How to reshape a dataframe to the largest possible square after 
# removing the negative values?
# Reshape df to the largest possible square with negative values removed.
# Drop the smallest values if need be. The order of the positive numbers
# in the result should remain the same as the original.
# method 1 mine
np.random.seed(100)
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
df = np.where(df<0, np.nan, df)
df = np.array([i[~np.isnan(i)] for i in df])
minimal_len = np.min([i.shape[0] for i in df])
# cut col
df = df[0:minimal_len]
# cut rows
df = np.array([i[:minimal_len] for i in df])
print(df)
# method 2 their
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
print(df)
# Solution

# Step 1: remove negative values from arr
arr = df[df > 0].values.flatten()
arr_qualified = arr[~np.isnan(arr)]
# Step 2: find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))
# Step 3: Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

[[ 4. 47. 28. 32. 33.]
 [ 4. 40. 38.  7. 11.]
 [39. 47. 29. 27. 45.]
 [35. 43. 33.  7. 36.]
 [27. 19. 18. 24. 44.]]
    0   1   2   3   4   5   6   7   8   9
0  -3  25  25  15  -4  -8  47   0 -10 -12
1  10  -8  -2  24  37 -20  34  46  -4 -15
2  31  14  47  34 -19  -6  13   0  20   4
3  38   8 -13 -18  43 -18  -3  33  10  47
4   8  17  -3 -10  -7   5  46  -5  -9  18
5   2  35  37  31  28  33  -3  45  22  24
6  -4  31  34  35  22  41  17 -18  42  -4
7  33  27  28 -11  29  33  14 -17  -9  29
8   9  16  47   6  32  16  11  48  41  16
9  22  -7  28  12  18  20  33  -6  18  17
[[25. 25. 15. 47. 10. 24. 37. 34.]
 [46. 31. 14. 47. 34. 13. 20. 38.]
 [ 8. 43. 33. 10. 47.  8. 17. 46.]
 [18. 35. 37. 31. 28. 33. 45. 22.]
 [24. 31. 34. 35. 22. 41. 17. 42.]
 [33. 27. 28. 29. 33. 14. 29.  9.]
 [16. 47. 32. 16. 11. 48. 41. 16.]
 [22. 28. 12. 18. 20. 33. 18. 17.]]


In [0]:
# 56. How to swap two rows of a dataframe?
# Swap rows 1 and 2 in df.
df = pd.DataFrame(np.arange(25).reshape(5, -1))
temp = df.iloc[1].copy
a, b = df.iloc[1, :].copy(), df.iloc[2, :].copy()
df.iloc[1, :], df.iloc[2, :] = b, a

In [329]:
# 57. How to reverse the rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df = df.iloc[::-1]
print(df)

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [330]:
# 58. How to create one-hot encodings of a categorical
# variable (dummy variables)?
# Get one-hot encodings for column 'a' in the dataframe df and 
# append it as columns.
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
a = pd.get_dummies(df['a'])
a

0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1

In [331]:
# 59.Which column contains the highest number of row-wise maximum values?
#Obtain the column name with the highest number of row-wise maximum’s in df.
# method 1 fast
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
# Solution
print('Column with highest row maxes: ',
      df.apply(np.argmax, axis=1).value_counts().index[0])
# method 2
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
max_values = [value[value.idxmax()] for _, value in df.iterrows()] 
# column idx
a = df.isin(max_values).sum().idxmax()
print(a)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:56: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  return getattr(obj, method)(*args, **kwds)


Column with highest row maxes:  1
0


In [0]:
# 60. How to create a new column that contains the row number of 
# nearest column by euclidean distance?
# Create a new column such that, each row contains the row number of 
# nearest row-record by euclidean distance.
# in np: dist = numpy.linalg.norm(a-b)
# method 1
np.random.seed(100)
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1),
                  columns=list('pqrs'), index=list('abcdefghij'))
nearest_row = []
nearest_dist = []
for idx1, row1 in df.iterrows():
    a = np.array([np.linalg.norm(row1-row2) for idx, row2 in df.iterrows()])
    nearest_row.append(np.where(a == np.partition(a, 1)[1])[0][0])
    nearest_dist.append(np.partition(a, 1)[1])
df['nearest_row'] = nearest_row
df['nearest_dist'] = nearest_dist
# method 2
np.random.seed(100)
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1),
                  columns=list('pqrs'), index=list('abcdefghij'))
# Solution
import numpy as np
# init outputs
nearest_rows = []
nearest_distance = []
# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))
df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

In [333]:
# 61. How to know the maximum possible correlation value of each column
# against other columns?
# Compute maximum possible absolute correlation value of each column against
# other columns in df
np.random.seed(100)
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1),
                  columns=list('pqrstuvwxy'), index=list('abcdefgh'))
cor = np.abs(df.corr())
cor = cor.apply(lambda x: sorted(x)[-2])
cor

p   0.4548
q   0.5120
r   0.5120
s   0.9052
t   0.4464
u   0.9052
v   0.5127
w   0.3948
x   0.5471
y   0.5047
dtype: float64

In [0]:
# 62. How to create a column containing the minimum 
# by maximum of each row?
# Compute the minimum-by-maximum for every row of df.
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
#method 1
df['min/max'] = np.min(df, axis=1)/np.max(df, axis=1)
#method 2 
df['min/max'] = [row.min()/row.max() for idx, row in df.iterrows()]

In [335]:
%%time
# 63. How to create a column that contains the penultimate value in each row?
# Create a new column 'penultimate' which has the second largest value of
# each row of df.
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
# np.partition(a, 1)[1]
# [np.linalg.norm(row1-row2) for idx, row2 in df.iterrows()]
df['penultimate'] = [np.partition(row, -2)[-2] for idx, row in df.iterrows()]
df

CPU times: user 5.82 ms, sys: 0 ns, total: 5.82 ms
Wall time: 7.03 ms


In [336]:
# 64. How to normalize all columns in a dataframe?
# ormalize all columns of df by subtracting the column mean and
# divide by standard deviation.
# Range all columns of df such that the minimum value in each colum
# is 0 and max is 1.
from sklearn.preprocessing import StandardScaler, MinMaxScaler
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
# subtracting the column mean and divide by standard deviation.
scaler = StandardScaler(copy = False)
df = scaler.fit_transform(df)
# minimum value in each colum is 0 and max is 1
scaler = MinMaxScaler(copy = False)
df = scaler.fit_transform(df)
df

array([[0.51612903, 0.        , 0.46875   , 0.5505618 , 0.38461538,
        0.01162791, 0.        , 0.25      , 0.31521739, 0.11111111],
       [1.        , 0.74358974, 0.109375  , 0.53932584, 0.42307692,
        0.8255814 , 0.26315789, 1.        , 1.        , 1.        ],
       [0.89247312, 0.79487179, 0.65625   , 1.        , 0.42307692,
        0.46511628, 0.02631579, 0.22916667, 0.89130435, 0.        ],
       [0.40860215, 0.3974359 , 0.53125   , 1.        , 0.        ,
        0.41860465, 0.98684211, 0.        , 0.        , 0.75      ],
       [0.44086022, 0.44871795, 0.        , 0.80898876, 1.        ,
        0.12790698, 1.        , 0.58333333, 0.73913043, 0.61111111],
       [0.        , 1.        , 1.        , 0.06741573, 0.98076923,
        0.        , 1.        , 0.8125    , 0.42391304, 0.11111111],
       [0.37634409, 0.21794872, 0.        , 0.        , 0.48076923,
        0.98837209, 0.82894737, 0.875     , 1.        , 0.55555556],
       [0.47311828, 0.05128205, 0.21875  

In [338]:
# 65. How to compute the correlation of each row with the suceeding row?
# Compute the correlation of each row of df with its succeeding row.
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
cor = np.abs(df.T.corr())
cor_row_to_row = [row[idx+1] for idx, row in cor.iterrows() if (idx < 7)]
cor_row_to_row

[0.2941474943839492,
 0.11578553346964404,
 0.5454464330014843,
 0.8014249504481016,
 0.7234335388804092,
 0.02404312538329484,
 0.26711613030210735]

In [339]:
# 66. How to replace both the diagonals of dataframe with 0?
# Replace both values in both diagonals of df with 0.
# method 1
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
# method 2
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df.values[[np.arange(df.shape[0])]*2] = 0
df.values[np.arange(df.shape[0]), [np.flipud(np.arange(df.shape[0]))]] = 0
df

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  import sys


0   1   2   3   4   5   6   7   8   9
0   0  40  83   4  34  38  42  54   7   0
1  19   0  95  20  85  74  16  78   0  48
2  38  58   0  60  54  47  48   0  46  79
3  61  45   9   0   8  54   0  65  35   5
4  13  41  35  94   0   0  83  13  86  24
5  68  61  80  10   0   0  73  17  92  27
6  28  89  35   0  59  75   0  45  55  84
7   8  52   0  42  30  76  71   0  15  10
8  79   0  28  56   3  21  47  59   0  61
9   0  66  67  21  65  79  68   9  13   0

In [340]:
# 67. How to get the particular group of a groupby dataframe by key?
# This is a question related to understanding of grouped dataframe. From 
# df_grouped, get the group belonging to 'apple' as a dataframe.
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})
df_grouped = df.groupby(['col1'])
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)

    col1   col2  col3
0  apple 0.3299     2
3  apple 0.7782    12
6  apple 0.6526     6


In [341]:
# 68. How to get the n’th largest value of a column when grouped by 
# another column?
# In df, find the second largest value of 'taste' for 'banana'
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'taste': np.random.randint(0, 15, 9)})
df_grouped = df['taste'].groupby(df['fruit'])
df_grouped.get_group('banana').sort_values().iloc[-2]


0

In [345]:
# 69. How to compute grouped mean on pandas dataframe and keep the 
# grouped column as another column (not index)?
# In df, Compute the mean price of every fruit, while keeping the fruit
# as another column instead of an index.
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
df_grouped = df['price'].groupby(df['fruit']).mean()
df_grouped

fruit
apple    4.6667
banana   7.6667
orange   5.6667
Name: price, dtype: float64

In [0]:
# 70. How to join two dataframes by 2 columns 
# so they have only the common rows?
# Join dataframes df1 and df2 by ‘fruit-pazham’ and ‘weight-kilo’.
#method 1 fast
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})
df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])
#method 2
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
df = pd.concat([df1, df2], axis=1)
df = df.dropna()
df

In [372]:
# 72. How to get the positions where values of two columns match?
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
            'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
np.where(df['fruit1'] == df['fruit2'])

(array([0, 4, 6, 8]),)

In [406]:
# 73. How to create lags and leads of a column in a dataframe?
# Create two new columns in df, one of which is a lag1 (shift column a
# down by 1 row) of column ‘a’ and the other is a lead1 (shift column b 
# up by 1 row).
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4),
                  columns = list('abcd'))
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
df

a   b   c   d  a_lag1  b_lead1
0  87  66  96  89     nan   7.0000
1  52   7  70  41 87.0000   6.0000
2  23   6  78  98 52.0000   4.0000
3  24   4  60  45 23.0000  65.0000
4  96  65   6  11 24.0000      nan

In [411]:
# 74. How to get the frequency of unique values in the entire dataframe?
# Get the frequency of unique values in the entire dataframe df.
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4),
                  columns = list('abcd'))
values, count = np.unique(df, return_counts=True)


CPU times: user 1.72 ms, sys: 0 ns, total: 1.72 ms
Wall time: 1.56 ms


In [437]:
# 75. How to split a text column into two separate columns?
# Split the string column in df to form a dataframe with 3 columns as shown.
df = pd.DataFrame(["STD, City    State",
                "33, Kolkata    West Bengal",
                "44, Chennai    Tamil Nadu",
                "40, Hyderabad    Telengana",
                "80, Bangalore    Karnataka"], columns=['row'])
df = df['row'].str.split(' ', expand=True)
df

0          1 2 3 4          5       6
0  STD,       City            State    None
1   33,    Kolkata             West  Bengal
2   44,    Chennai            Tamil    Nadu
3   40,  Hyderabad        Telengana    None
4   80,  Bangalore        Karnataka    None